### PR TITLE
Update clang-format to 16

### PR DESCRIPTION
**Pull request by EZ64cool**
### Description

Upgrade clang-format used in actions to 16

### Motivation and Context

With changes introduced in https://github.com/obsproject/obs-plugintemplate/pull/82 clang-format 16 is now required. Using the current version of 13 will result in a `.clang-format:115:3: error: unknown enumerated scalar` error

### How Has This Been Tested?

I have made small edits to code files which should trigger the github action which I will then revert.
I have also implemented this change into my own plugin after merging latest. https://github.com/EZ64cool/obs-hadowplay/actions/workflows/pr-pull.yaml?query=branch%3Amerging_template

### Types of changes

 - Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [X] All commit messages are properly formatted and commits squashed where appropriate.
- [X] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — APPROVED** [review]
Looks fine at a glance. @PatTheMav ?

**Comment by PatTheMav** [comment]
Commits need to be squashed and the experimental change reverted before that.

**Comment by RytoEX** [comment]
> Commits need to be squashed and the experimental change reverted before that.

Ah, I didn't see the commits. Yes, this feedback needs to be addressed.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Per @PatTheMav :
> Commits need to be squashed and the experimental change reverted before that.

**Comment by EZ64cool** [comment]
Thanks, first time contributing so sorry for the mess. I'll make a seperate FQ for running clang-format on other relevant files to keep this neat.

**Review by PatTheMav — APPROVED** [review]

**Pull request merged**
