### PR TITLE
Target OBS 30.0.2

### PR DESCRIPTION
**Pull request by sorayuki**
### Motivation and Context

Build towards the latest release of obs-studio.

### How Has This Been Tested?

It works for my obs-multi-rtmp plugin.

### Types of changes

Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
@RytoEX LGTM - do we want to merge this now or wait for a patch release of OBS Studio first?

**Comment by RytoEX** [comment]
> @RytoEX LGTM - do we want to merge this now or wait for a patch release of OBS Studio first?

We can just merge this now and then quickly update it to 30.0.2 if needed.

**Comment by PatTheMav** [comment]
Please squash commits and use a properly formatted commit message - in this case I would suggest something along the lines of "buildspec: Update OBS Studio dependency to 30.0.2"

**Review by RytoEX — APPROVED** [review]
Looks fine at a glance. @PatTheMav ?

**Review by PatTheMav — APPROVED** [review]

**Pull request merged**
