### PR TITLE
cmake: when libobs-dev installs as LibObs instead of libobs as expected

### PR DESCRIPTION
**Pull request by MartinBagge**
### Description
Changed the cmake file to look also for LibObs, because when I installed the libobs-dev package on my linux system it was under LibObs instead of libobs. It was unable to locate it and this should fix it. 
It will first look for libobs and is that does not exist look for LibObs and create an alias to libobs.
Also changed to no longer look for OBS::libobs as the alias is never created, so that is just libobs instead.

### Motivation and Context
Was unable to build plugin, this seems to solve the issue.

### How Has This Been Tested?
Tested on ubuntu 22.04 LTS, on two different machines.

### Types of changes
Bug fix (non-breaking change which fixes an issue)
Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Wouldn't it be better to just make this check case-insensitive rather than trying to match two explicit casing scenarios?

**Comment by gxalpha** [comment]
Where is `libobs-dev` from? Who's maintaining it?

`libObs` and the missing `OBS::` alias sounds a lot like some (potentially old) third-party package.

**Comment by gxalpha** [comment]
To answer my own question, [libobs-dev on jammy](https://packages.ubuntu.com/jammy/libobs-dev) is OBS 27.2 because Ubuntu packages never get updated once they are released, which is incredibly annoying (and why our PPA for the whole app exists). As far as I remember, the plugintemplate requires at least OBS 28.

I think the better solution to the problem is to update to kinetic (although that package isn’t maintained by us either) or to build OBS yourself. That being said, pinging @PatTheMav as he might have opinions on this as well.

**Comment by PatTheMav** [comment]
This is by design `LibObs` is the outdated and incompatible library identifier that is not compatible with our updated CMake build system. Only the "modern" libobs cmake package is supported.

The correct solution is for package managers to update `libobs-dev` with OBS 28 as its basis. The plugintemplate _should_ specify that as the minimum version then (so the build process via the script fails otherwise), which probably also requires extending the `Aptfile` support to understand minimum version specifiers (but that's a small change).

**Comment by PatTheMav** [comment]
@tytan652 I'd need some guidance/assistance here to figure out an "official" workflow expected for Linux plugins and an almost-rework of the Linux build scripts.

**Pull request closed without merging**
