### PR TITLE
Move UUIDs to CMakeLists.txt

### PR DESCRIPTION
**Pull request by norihiro**
### Description

Move the UUIDs to the top of the CMakeLists.txt to clarify plugin developers to change for them.

Also put the UUIDs into `buildspec.json` so that CMakeLists.txt can be overwritten by script and revised build-scripts to overwrite CMakeLists.txt.

### Motivation and Context

The UUIDs for macOS installers and Windows installer should be differentiated for each plugin.

### How Has This Been Tested?

I introduced this change into my plugins (also modified a lot) and released packages. For example,
- https://github.com/norihiro/obs-color-monitor/commit/1d93deabf9af98c0fef5e93f471b895143df0849

The scripts to overwrite CMakeLists.txt is tested on this build. Settings in CMakeLists.txt was filled with invalid text. Then, run the script and checked the settings are overwritten after the script has run.
- https://github.com/norihiro/obs-plugintemplate/actions/runs/3099297250

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by norihiro** [comment]
I haven't noticed this setting. I think this is also required to be modified by plugin developers.
https://github.com/obsproject/obs-plugintemplate/blob/056422b2614fed1037bc1f19e0e468165e3068ea/cmake/bundle/windows/installer-Windows.iss.in#L7-L10

**Comment by exeldro** [comment]
maybe also use the UUID for https://github.com/obsproject/obs-plugintemplate/blob/master/cmake/bundle/windows/installer-Windows.iss.in#L10

**Comment by norihiro** [comment]
I'm wondering is that one close blacket is missing. Is this just a typo or that's the right syntax.
https://github.com/obsproject/obs-plugintemplate/blob/056422b2614fed1037bc1f19e0e468165e3068ea/cmake/bundle/windows/installer-Windows.iss.in#L10

**Review by PatTheMav — APPROVED** [review]
Changes look good - food for thought:

As we already modify the CMakeLists.txt to update the version in the `project` call from the build script (after reading buildspec.json) it would make sense to set the UUIDs in the json as well and have the build script update the CMake file accordingly.

**Comment by PatTheMav** [comment]
I'm referring to these specific parts of the build scripts:

https://github.com/obsproject/obs-plugintemplate/blob/056422b2614fed1037bc1f19e0e468165e3068ea/.github/scripts/.build.zsh#L176

https://github.com/obsproject/obs-plugintemplate/blob/056422b2614fed1037bc1f19e0e468165e3068ea/.github/scripts/Build-Windows.ps1#L60

**Comment by RytoEX** [comment]
Any further progress on this or thoughts on @PatTheMav 's feedback?

**Comment by norihiro** [comment]
After the last review by @PatTheMav, I have updated them.
- AppId for Windows installer is also set through cmake.
- 3 UUIDs in CMakeLists.txt are replaced with the settings in buildspec.json.

**Review by PatTheMav — CHANGES_REQUESTED** [review]
Code-wise this looks good, I'd just prefer if we use lowercase with hyphens or camelcase in the JSON (as that's more common for JSON files) instead of the all uppercase CMake variable names.

**Review by PatTheMav — APPROVED** [review]

**Comment by PatTheMav** [comment]
@norihiro Could you update the field names in the buildspec file to say "windowsAppId" instead of "windows-app-id" (same for the other two added fields) per my last comment? Otherwise this looked good to merge then.

**Comment by paulpv** [comment]
This PR looks great @norihiro. Is it final and ready to review & merge?

**Comment by norihiro** [comment]
Resolved the conflict and revise usage of `sed`; instead of having multiple `-e` option, running `sed` for each substitution to follow the other commit 79ef199c67453bfa.

**Comment by PatTheMav** [comment]
> Resolved the conflict and revise usage of `sed`; instead of having multiple `-e` option, running `sed` for each substitution to follow the other commit [79ef199](https://github.com/obsproject/obs-plugintemplate/commit/79ef199c67453bfac4a56517eb8a0613e8c2a7e1).

I would've been fine with using the `-e` option as that reduces the overhead of calling `sed` multiple times, but it wasn't critical enough to hold up the other PR over it, so that's up to you.

**Comment by glikely** [comment]
Can we instead drop sed entirely and have cmake read buildspec itself? Modifying checked in files like cmakelist.txt causes problems for multiple build directories. But, as of version 3.19, Cmake has native json support so that sed isn't necessary. I've drafted a patch here that shows the change needed:

https://github.com/obsproject/obs-plugintemplate/commit/57977e3fe9939328ecdf7eb6e42d8fd92e3ceb6f

**Comment by PatTheMav** [comment]
> Can we instead drop sed entirely and have cmake read buildspec itself? Modifying checked in files like cmakelist.txt causes problems for multiple build directories. But, as of version 3.19, Cmake has native json support so that sed isn't necessary. I've drafted a patch here that shows the change needed:
> 
> [57977e3](https://github.com/obsproject/obs-plugintemplate/commit/57977e3fe9939328ecdf7eb6e42d8fd92e3ceb6f)

That's actually what we're introducing on obs-studio, but for multiple reasons we have to use CMake 3.16 as the lowest common denominator, so relying on that for all platforms is a no-go until our oldest supported Ubuntu version ships a more modern CMake.

**Comment by norihiro** [comment]
> Modifying checked in files like cmakelist.txt causes problems for multiple build directories.
I'm also concerning this because if this will results `git status` or `git describe --dirty` to flag the change.

Instead of reading from CMakeLists.txt, how about writing into an untracked file such as `buildspec-generated.cmake` and include from CMakeLists.txt? This might be separated to an individual commit though.

**Comment by glikely** [comment]
> That's actually what we're introducing on obs-studio, but for multiple reasons we have to use CMake 3.16 as the lowest common denominator, so relying on that for all platforms is a no-go until our oldest supported Ubuntu version ships a more modern CMake.

I feared something like that would be the case. What is the policy for supported Ubuntu versions? 
I see that Focal (20.04LTS) ships Cmake 3.16, and Jammy (22.04LTS) is shipping 3.22. Does it need to wait until the 2024 LTS is released to make that change?

**Comment by glikely** [comment]
> > Modifying checked in files like cmakelist.txt causes problems for multiple build directories.
> > I'm also concerning this because if this will results `git status` or `git describe --dirty` to flag the change.
> 
> Instead of reading from CMakeLists.txt, how about writing into an untracked file such as `buildspec-generated.cmake` and include from CMakeLists.txt? This might be separated to an individual commit though.

That would work for me, and yes it makes sense to do that is a separate commit than in this PR

**Comment by paulpv** [comment]
Is this ready to merge, or as @PatTheMav mentions in https://github.com/obsproject/obs-plugintemplate/pull/76...
> Closes https://github.com/obsproject/obs-plugintemplate/pull/41.
...is this PR now deprecated.

CC @norihiro

**Pull request closed without merging**
