### PR TITLE
Refactor find_qt CMake macro to select Qt version automatically if not specified

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Same changes as https://github.com/obsproject/obs-studio/pull/6782 but for the template.

### Motivation and Context

Allow to automatically use whether Qt5 or Qt6 is available and if both are present **prefer Qt6**.

### How Has This Been Tested?

https://github.com/obsproject/obs-studio/pull/6782 proves that the macro is functional.

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
I don't know how to fix the issue with the unlink of git on macOS CIs.

**Comment by tytan652** [comment]
Let's try by removing the workaround.

**Comment by tytan652** [comment]
Let's try `--no-upgrade` on brew.

**Comment by RytoEX** [comment]
CI is finally green. If @PatTheMav thinks this is good, then we can ship it.

**Review by PatTheMav — APPROVED** [review]
Looks like a carbon copy of the same macro on the main repo, so should be good.

**Comment by tytan652** [comment]
> Looks like a carbon copy of the same macro on the main repo, so should be good.

It is.

**Pull request merged**
