### PR TITLE
FIX for ubuntu as of december 5 of 2022

### PR DESCRIPTION
**Pull request by GabrielReyes136**
renaming this 2 lines make compilation possible on my machine

i installed the associated libraries by running

sudo apt-get install libobs-dev

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by GabrielReyes136** [comment]
i mainly wrote this to bring attention to the issue rather than introducing an official fix

**Comment by GabrielReyes136** [comment]
/usr/bin/ld: cannot find -lLibObs: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/obs-plugintemplate.dir/build.make:97: obs-plugintemplate.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/obs-plugintemplate.dir/all] Error 2
make: *** [Makefile:156: all] Error 2



when actually trying to build the file it appears as if you have to manually rename it to -libobs

**Comment by GabrielReyes136** [comment]
renamed line 54 to libobs instead of LibObs and the make file successfully produced an .so file

**Comment by RytoEX** [comment]
See also #55.

**Comment by Fenrirthviti** [comment]
Duplicate of #55

libobs-dev is a package that is not maintained by us, and is not supported as a build method. More information in duplicate PR.

**Pull request closed without merging**
