### PR TITLE
Auto generate plugin name in workflow

### PR DESCRIPTION
**Pull request by cg2121**
### Description
This generates the plugin name based on the name in the buildspec file.

### Motivation and Context
One less file for developers to change.

### How Has This Been Tested?
Ran workflow.

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — CHANGES_REQUESTED** [review]
Rather than assuming that the repo name is what the plugin maintainer wants to use for artifact names, I think it might make more sense to save the repo name to an intermediate variable and use that instead. With these changes, if a plugin maintainer wanted to use a different name, they'd have to change more places than the currently do.

@PatTheMav ?

**Comment by PatTheMav** [comment]
I think the idea is sound, however the plugin _name_ is defined in the `buildspec.json` file (the build script even updates `CMakeList.txt` with name and version with the values from it).

So IMO the "correct" change would be a step that parses the JSON file and sets that as an output variable that's then re-used throughout the workflow.

**Comment by PatTheMav** [comment]
@cg2121 I guess the most portable way would be to add code to the respective "Setup Environment" steps in the workflow to parse the buildspec file and then print that value to `$GITHUB_OUTPUT` so you can reuse it in the later workflow steps.

**Comment by cg2121** [comment]
Updated to use the suggestion by @PatTheMav

**Review by PatTheMav — APPROVED** [review]
Looks good to me.

**Pull request merged**
